config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'main#index'

  resources :long_goals do
    resources :short_goals
  end

  resources :users
  resource :session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/long_goal.rb
class LongGoal < ApplicationRecord
  has_many :short_goals
  belongs_to :user

  validates :goal, presence: true
  # yay validations!
end

app/models/short_goal.rb
class ShortGoal < ApplicationRecord
  belongs_to :long_goal
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :long_goals
  has_many :short_goals

  validates :username, presence: true
  validates :password, presence: true
  # awesome! if you want to check out password encryption for your app, this tutorial is supposedly good and fits with your users-from-scratch approach: https://www.sitepoint.com/rails-userpassword-authentication-from-scratch-part-i/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_current_user

  def get_current_user
    if User.exists?(session[:user_id])
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  
end

app/controllers/long_goals_controller.rb
class LongGoalsController < ApplicationController

# nice error handling here! sign em up! watch indentation tho
  def index
    if @current_user
    @long_goals = LongGoal.where(user_id: @current_user.id)
  else
    redirect_to '/users/new'
  end
  end

  def show
    @long_goal = LongGoal.find(params[:id])
  end

  def new
    redirect_to root_path unless @current_user
    # nice and concise
    @long_goal = LongGoal.new
  end

  def create
    redirect_to root_path unless @current_user
    @long_goal = LongGoal.new(long_goal_params)
    if @long_goal.save
      flash[:notice] = "Long-term goal was successfully created."
    redirect_to @long_goal
    else
      render :new
      flash[:alert] = "Must have a goal"
    end
  end


  def edit
    redirect_to root_path unless @current_user
    @long_goal = LongGoal.find(params[:id])
  end

  def update
    redirect_to root_path unless @current_user
    @long_goal = LongGoal.find(params[:id])
    @long_goal.update(long_goal_params)
    redirect_to @long_goal
  end

  def destroy
    redirect_to root_path unless @current_user
    @long_goal = LongGoal.find(params[:id])
    @long_goal.destroy
    redirect_to @long_goal
  end
  private

  def long_goal_params
    params.require(:long_goal).permit(:goal, :duedate, :image_url, :user_id)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    input_username = params[:user][:username]
    if User.exists?(username: input_username)
      @user = User.find_by(username: input_username)
        if @user.password === params[:user][:password]
          flash[:notice] = "You're signed in!"
          session[:user_id] = @user.id
          redirect_to root_path
        else
          flash[:alert] = "Wrong password!"
          redirect_to new_session_path
        end
      else
        flash[:alert] = "That user doesn't exist!"
      end
      # nice use and communicative use of flashes! good UX here
  end

  def destroy
    reset_session
    flash[:notice] = "You're signed out!"
    redirect_to :root
  end

# awesome way to handle logins!
end

app/controllers/short_goals_controller.rb
class ShortGoalsController < ApplicationController
  def show
    @short_goal = ShortGoal.find(params[:id])
    @long_goal = @short_goal.long_goal
  end

  def new
    redirect_to root_path unless @current_user
    @long_goal = LongGoal.find(params[:long_goal_id])
    @short_goal = ShortGoal.new
    # you could also @short_goal.new(long_goal: long_goal.id) and then in your short_goal new view use only @short_goal in your form_for. not necessarily any better but just another way to do it!
  end

  def create
    redirect_to root_path unless @current_user
    @long_goal = LongGoal.find(params[:long_goal_id])
    @short_goal = @long_goal.short_goals.new(short_goal_params)
    @short_goal.user = @current_user
    @short_goal.save!
    redirect_to @long_goal
    # can see that you are dealing 'fluently' with your models/resources here!
  end

  def edit
    redirect_to root_path unless @current_user
    @long_goal = LongGoal.find(params[:long_goal_id])
    @short_goal = ShortGoal.find(params[:id])
  end

  def update
    redirect_to root_path unless @current_user
    @long_goal = LongGoal.find(params[:long_goal_id])
    @short_goal = ShortGoal.find(params[:id])
    @short_goal.update(short_goal_params)
    redirect_to @long_goal
  end

  def destroy
    redirect_to root_path unless @current_user
    @long_goal = LongGoal.find(params[:id])
    @short_goal = ShortGoal.find(params[:id])
    @short_goal.destroy
    redirect_to @long_goal
  end

  private

  def short_goal_params
    params.require(:short_goal).permit(:goal, :scheduled_date, :location)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]



  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

#careful with indentation! not a huge deal makes a difference in readability
  def create
    @user = User.new(user_params)
    if @user.save
    session[:user_id] = @user.id
    redirect_to root_path
  else
    flash.now[:alert] = "Fields are incomplete"
    render :new
  end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_url unless @current_user == @user
  end

  def update
    @user = User.find(params[:id])
    redirect_to root_url unless @current_user == @user
    @user.update(user_params)
    redirect_to users_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

  def logged_in_user
    unless logged_in?
      #  this errored out for me; maybe unless @current_user would work better?
      flash[:alert] = "Please log in."
      render :new
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user === current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/long_goals_helper.rb
module LongGoalsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/short_goals_helper.rb
module ShortGoalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uppercut</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Alegreya+Sans' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <header>
      <div class='navbar'>
        <ul>
          <li><strong><%= link_to 'UPPERCUT 👊', main_index_path %></strong></li>
          <% if @current_user %>
            <strong>
              <%= link_to "Hey there, #{@current_user.username}!  😆", user_path(@current_user) %>
            </strong>
            <li class='sign'><strong><%= link_to 'SIGN OUT', session_path, method: :delete %></strong></li>
          <% else %>
            <li class='sign'><strong><%= link_to 'SIGN IN', new_session_path %> </strong></a></li>
            <li class='sign'><strong><%= link_to 'SIGN UP', new_user_path %></strong></li>
          <% end %>
          <li class='sign'><strong><%= link_to 'LONG-TERM GOALS', long_goals_path %></strong></li>
        </ul>
      </div>
    </header>
    <br>
    <% flash.each do |type, message| %>
      <p class='<%= type %>'><%= message %></p>
    <% end %>
    <br>

    <div class='background'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/long_goals/_form.html.erb
<%= form_for @long_goal do |f| %>

  <%= f.label :goal %>
  <%= f.text_field :goal %>

  <%= f.label :duedate %>
  <%= f.date_field :duedate %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.hidden_field(:user_id, :value => @current_user.id) %>
<%= f.submit %>
<% end %>

app/views/long_goals/edit.html.erb
<%= render 'form' %>

</p><%= link_to '(-) Remove Long-term Goal', long_goal_path(@long_goal),
    method: :delete,
    data: {confirm: "Once this is deleted, you must re-enter your goal if you would ever like to bring it back.  Continue?"} %></p>

app/views/long_goals/index.html.erb
<%= link_to('(+) Create new long-term goal', new_long_goal_path(@long_goal)) if @current_user %>

<ol>

<% @long_goals.each do |long| %>
  <li><%= link_to long.goal, long_goal_path(long) %> <%= link_to('(edit)', edit_long_goal_path(long)) if @current_user %> </li>
<% end %>
</ol>

app/views/long_goals/new.html.erb
<%= render 'form' %>

app/views/long_goals/show.html.erb
<h2><%= @long_goal.goal %></h2>
<p><%= @long_goal.duedate %></p>
<p><%= image_tag @long_goal.image_url %></p>

<p><%= link_to('(+) Add short term goal', new_long_goal_short_goal_path(@long_goal, @short_goal)) if @current_user %></p>
<% @long_goal.short_goals.each do |short_goal| %>
  <p><%= link_to short_goal.goal, long_goal_short_goal_path(@long_goal, short_goal) %> <%= link_to('(edit)', edit_long_goal_short_goal_path(@long_goal, short_goal)) if @current_user %></p>
<% end %>

<%= link_to ' ⬅ back', long_goals_path %>

app/views/main/index.html.erb
<div class='welcomebox'>
<h6>
  <%= link_to 'Welcome to Uppercut.  Please click here to begin your journey to creating the life you want.', long_goals_path %>
</h6>
</div>

app/views/short_goals/_form.html.erb
<%= form_for [@long_goal, @short_goal] do |f| %>

  <%= f.label :goal %>
  <%= f.text_field :goal %>

  <%= f.label :scheduled_date %>
  <%= f.date_field :scheduled_date %>

  <%= f.label :location %>
  <%= f.text_field :location %>

<%= f.submit %>
<% end %>

app/views/short_goals/edit.html.erb
<%= render 'form' %>

<%= link_to '(-) Remove Short-term Goal', long_goal_short_goal_path(@short_goal),
    method: :delete,
    data: {confirm: 'Are you sure that you would like to permanently remove this goal?'}%>

app/views/short_goals/new.html.erb
<h2>Short term goal to achieve the goal to <%= @long_goal.goal.downcase %>. </h2>
<!-- Nice use of downcase: I like the language here, feels natural: nice UX -->
<%= form_for [@long_goal, @short_goal] do |f| %>
<!-- looks good! I like that this form is merging the params; see comment in controller also -->
  <%= f.label :goal %>
  <%= f.text_field :goal %>

  <%= f.label :scheduled_date %>
  <%= f.date_field :scheduled_date %>

  <%= f.label :location %>
  <%= f.text_field :location %>

<%= f.submit %>
<% end %>

app/views/short_goals/show.html.erb
<p>Short-term goal : <%= @short_goal.goal %> by <%= @short_goal.scheduled_date %></p>

<p>Location: <%= @short_goal.location %></p>
<p>To get closer to <%= @short_goal.long_goal.goal.downcase %>!</p>

app/views/users/edit.html.erb
<h2>Edit Your Profile</h2>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

<%= f.submit "Submit" %>
<% end %>

app/views/users/index.html.erb
<h2>Users</h2>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<div id="newuserform">
<%= form_for @user do |f| %>
  <div class='userform'>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class='userform'>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

<%= f.submit "Submit" %>
<% end %>
</div>

app/views/users/show.html.erb
<h2><%= @user.username %> <%= link_to("(edit)", edit_user_path(@user)) if @current_user == @user %></h2>